# Generated by Django 2.0.6 on 2018-09-15 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='photos')),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='news.News')),
            ],
        ),
    ]
